# Generated by Django 5.2.4 on 2025-07-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='user',
            name='marketing_consent1',
            field=models.BooleanField(default=False, verbose_name='Согласие на рассылку'),
        ),
        migrations.AddField(
            model_name='user',
            name='marketing_consent2',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Логин'),
        ),
    ]
