# Generated by Django 5.2.4 on 2025-08-04 14:24

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='url')),
                ('image', models.ImageField(upload_to='images/category/', verbose_name='Изображение')),
                ('available', models.BooleanField(default=True, verbose_name='Доступность')),
                ('description', models.TextField(blank=True, max_length=100, verbose_name='Описание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('popularity', models.PositiveIntegerField(blank=True, default=0, verbose_name='Популярность')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region='RU', verbose_name='Телефон')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('specialization', models.CharField(db_index=True, max_length=100, verbose_name='Специализация')),
                ('comment', models.TextField(blank=True, max_length=1000, verbose_name='Комментарий')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('invited', 'Приглашен'), ('rejected', 'Отклонен'), ('hired', 'Нанят'), ('spam', 'Спам')], default='new', max_length=20, verbose_name='Статус')),
                ('created_by_client', models.BooleanField(default=False, verbose_name='Создано клиентом')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
                'indexes': [models.Index(fields=['city', 'specialization'], name='main_jobapp_city_91d7a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region='RU', verbose_name='Телефон')),
                ('image', models.ImageField(blank=True, upload_to='images/orders/', verbose_name='Фото')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Адрес')),
                ('comment', models.TextField(blank=True, max_length=100, verbose_name='Комментарий')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('canceled', 'Отменен'), ('in_work', 'В работе'), ('completed', 'Выполнен'), ('spam', 'Спам')], default='new', max_length=20, verbose_name='Статус')),
                ('created_by_client', models.BooleanField(default=False, verbose_name='Создано клиентом')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'indexes': [models.Index(fields=['status', 'phone', 'date_created'], name='main_order_status_433f25_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Продукт')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='url')),
                ('image', models.ImageField(blank=True, upload_to='images/products/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('available', models.BooleanField(default=True, verbose_name='Доступность')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('popularity', models.PositiveIntegerField(blank=True, default=0, verbose_name='Популярность')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Услуга')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='url')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('available', models.BooleanField(default=True, verbose_name='Доступность')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('popularity', models.PositiveIntegerField(blank=True, default=0, verbose_name='Популярность')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, max_length=50, verbose_name='Фамилия')),
                ('midle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region='RU', verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='Город')),
                ('experience', models.PositiveIntegerField(help_text='В годах', verbose_name='Опыт работы')),
                ('image', models.ImageField(blank=True, upload_to='images/employees/', verbose_name='Фото')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('date_hired', models.DateField(blank=True, null=True, verbose_name='Дата приема на работу')),
                ('status', models.CharField(choices=[('trainee', 'Стажировка'), ('active', 'Основной состав'), ('vacation', 'В отпуске'), ('sick_leave', 'На больничном'), ('fired', 'Уволен'), ('remote', 'Удалённая работа'), ('part_time', 'Частичная занятость'), ('maternity', 'Декретный отпуск'), ('business_trip', 'В командировке')], default='active', max_length=20, verbose_name='Статус')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='url')),
                ('available', models.BooleanField(default=True, verbose_name='Доступность')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.specialization', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['available', 'name'], name='main_produc_availab_83d243_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['available', 'name'], name='main_servic_availab_3587a7_idx'),
        ),
    ]
