# Generated by Django 5.2.4 on 2025-07-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by_client',
            field=models.BooleanField(default=False, verbose_name='Создано клиентом'),
        ),
    ]
