# Generated by Django 5.2.4 on 2025-08-06 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_images',
            field=models.ImageField(blank=True, upload_to='images/orders/additional/', verbose_name='Дополнительные фото'),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Полный адрес'),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.employee', verbose_name='Назначенный мастер'),
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Полное имя'),
        ),
        migrations.AddField(
            model_name='order',
            name='work_description',
            field=models.TextField(blank=True, verbose_name='Описание работ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('canceled', 'Отменен'), ('in_work', 'В работе'), ('completed', 'Выполнен'), ('spam', 'Спам'), ('failed', 'Не удалось связаться'), ('callback', 'Перезвонить')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
