# Generated by Django 5.2.4 on 2025-08-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order_created_by_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='created_by_client',
            field=models.BooleanField(default=False, verbose_name='Создано клиентом'),
        ),
    ]
