# Generated by Django 5.2.4 on 2025-07-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_popularity_alter_category_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('phone', models.CharField(db_index=True, max_length=50, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Адрес')),
                ('comment', models.TextField(blank=True, max_length=100, verbose_name='Комментарий')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('canceled', 'Отменен'), ('in_work', 'В работе'), ('completed', 'Выполнен'), ('spam', 'Спам')], default='new', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='popularity',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Популярность'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['available', 'name'], name='main_produc_availab_83d243_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'phone', 'created'], name='main_order_status_3e859e_idx'),
        ),
    ]
