# Generated by Django 5.2.4 on 2025-08-06 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_order_first_name_orderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='categories',
            field=models.ManyToManyField(blank=True, to='main.category', verbose_name='Категории работ'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product', verbose_name='Товар/Услуга'),
        ),
    ]
