# Generated by Django 5.2.4 on 2025-07-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_alter_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='main_order_status_3e859e_idx',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_update',
            new_name='date_updated',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'phone', 'date_created'], name='main_order_status_433f25_idx'),
        ),
    ]
