# Generated by Django 5.2.4 on 2025-08-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_employee_categories_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='specializations',
            field=models.ManyToManyField(blank=True, to='main.specialization', verbose_name='Специализации'),
        ),
    ]
