# Generated by Django 5.2.4 on 2025-08-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_category_specializations'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='products',
            field=models.ManyToManyField(blank=True, to='main.product', verbose_name='Товары'),
        ),
        migrations.AddField(
            model_name='employee',
            name='services',
            field=models.ManyToManyField(blank=True, to='main.service', verbose_name='Услуги'),
        ),
    ]
