# Generated by Django 5.2.4 on 2025-08-06 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_employee_products_employee_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, related_name='orders_new', to='main.employee', verbose_name='Назначенные мастера'),
        ),
        migrations.AddField(
            model_name='order',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='orders_new', to='main.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='orders_new', to='main.product', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='order',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_old', to='main.employee', verbose_name='Мастер (старый)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_old', to='main.category', verbose_name='Категория (старое)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_old', to='main.product', verbose_name='Товар (старый)'),
        ),
    ]
