# Generated by Django 5.2.4 on 2025-08-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order_assigned_employees_order_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='specialization_set', to='main.category', verbose_name='Категории'),
        ),
    ]
