# Generated by Django 5.2.4 on 2025-07-25 11:30

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_order_image_alter_order_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="date_updated",
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                ("age", models.PositiveIntegerField(verbose_name="Возраст")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        db_index=True,
                        max_length=128,
                        region="RU",
                        verbose_name="Телефон",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                (
                    "specialization",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Специализация"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="Комментарий"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("invited", "Приглашен"),
                            ("rejected", "Отклонен"),
                            ("hired", "Нанят"),
                            ("spam", "Спам"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Анкета",
                "verbose_name_plural": "Анкеты",
                "indexes": [
                    models.Index(
                        fields=["city", "specialization"],
                        name="main_jobapp_city_91d7a8_idx",
                    )
                ],
            },
        ),
    ]
