# Generated by Django 5.2.4 on 2025-08-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_specialization_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='midle_name',
            new_name='middle_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='specializations',
        ),
        migrations.RemoveField(
            model_name='order',
            name='additional_images',
        ),
        migrations.RemoveField(
            model_name='order',
            name='assigned_employee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AlterField(
            model_name='order',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, to='main.employee', verbose_name='Назначенные мастера'),
        ),
        migrations.AlterField(
            model_name='order',
            name='categories',
            field=models.ManyToManyField(blank=True, to='main.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, to='main.product', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='categories',
            field=models.ManyToManyField(blank=True, to='main.category', verbose_name='Категории'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status', 'available'], name='main_employ_status_143719_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['specialization', 'city'], name='main_employ_special_95fd95_idx'),
        ),
    ]
