# Generated by Django 5.2.4 on 2025-07-26 08:40

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_order_date_updated_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, max_length=50, verbose_name='Фамилия')),
                ('midle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region='RU', verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='Город')),
                ('specialization', models.CharField(db_index=True, max_length=100, verbose_name='Специализация')),
                ('experience', models.PositiveIntegerField(help_text='В годах', verbose_name='Опыт работы')),
                ('image', models.ImageField(blank=True, upload_to='images/employees/', verbose_name='Фото')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('date_hired', models.DateField(blank=True, null=True, verbose_name='Дата приема на работу')),
                ('status', models.CharField(choices=[('trainee', 'Стажировка'), ('active', 'Основной состав'), ('vacation', 'В отпуске'), ('sick_leave', 'На больничном'), ('fired', 'Уволен'), ('remote', 'Удалённая работа'), ('part_time', 'Частичная занятость'), ('maternity', 'Декретный отпуск'), ('business_trip', 'В командировке')], default='active', max_length=20, verbose_name='Статус')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
