# Generated by Django 5.2.4 on 2025-07-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступность'),
        ),
    ]
