# Generated by Django 5.2.4 on 2025-08-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_midle_name_employee_middle_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='main_employ_special_95fd95_idx',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='specialization',
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['city'], name='main_employ_city_bd73eb_idx'),
        ),
        migrations.AddField(
            model_name='employee',
            name='specialization',
            field=models.ManyToManyField(to='main.specialization', verbose_name='Специализации'),
        ),
    ]
